services:
  # --- BASE DE DATOS: POSTGRESQL  ---
  db:
    image: postgres:16-alpine
    container_name: laravel-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=laravel_db
      - POSTGRES_USER=laravel_user
      - POSTGRES_PASSWORD=mi_password_seguro
    command: >
      postgres
      -c shared_buffers=12MB
      -c max_connections=5
      -c work_mem=1MB
      -c maintenance_work_mem=8MB
      -c autovacuum=off
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - apps-net

  # --- APLICACIÓN: LARAVEL 12 (PHP 8.4 + FrankenPHP) ---
  app:
    image: serversideup/php:8.4-frankenphp
    container_name: laravel-app
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - apps-net
      - proxy-net
    volumes:
      - ./:/var/www/html:rw
      - ./caddyfile.d:/etc/frankenphp/caddyfile.d:ro
    environment:
      # --- Permisos de Usuario  ---
      - PUID=1000
      - PGID=1000

      # --- Configuración Proxy y Let's Encrypt  ---
      - VIRTUAL_HOST=prietoeats.orwin.servidorgp.somosdelprieto.com
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=prietoeats.orwin.servidorgp.somosdelprieto.com
      - LETSENCRYPT_EMAIL=orwinzavaleta@gmail.com

      # --- Laravel Core ---
      - APP_NAME=PrietoEats
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=https://prietoeats.orwin.servidorgp.somosdelprieto.com
      - APP_KEY=base64:SsOiYn8eIw/L294qRelrZRDcQvUIlE9XbOeeSExZ9qY=

      # --- Base de Datos ---
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=laravel_db
      - DB_USERNAME=laravel_user
      - DB_PASSWORD=mi_password_seguro

      # --- Drivers ---
      - SESSION_DRIVER=database
      - CACHE_STORE=file
      - QUEUE_CONNECTION=sync

      # --- Optimización de Memoria PHP ---
      - PHP_OPCACHE_ENABLE=1
      - PHP_INI_MEMORY_LIMIT=128M
      - PHP_INI_MAX_EXECUTION_TIME=120

       # === Límites de subida de archivos ===
      - PHP_INI_UPLOAD_MAX_FILESIZE=64M
      - PHP_INI_POST_MAX_SIZE=64M
      - PHP_INI_MEMORY_LIMIT=256M 

      # === Forzar detección de HTTPS detrás de proxy ===
      - HTTPS=on 
      - TRUSTED_PROXIES=*

networks:
  proxy-net:
    external: true
  apps-net:
    external: true